function esconderTudo(){
    $("#floresta").hide();   
    $("#animais").hide();
    $("#reflorestamento").hide();
    $("#lago").hide();
    $("#greenpeace").hide();
    $("#main_div").removeClass("principal");
    $("#voltar").show();
}

function sairJogos(){
    sairQueimadas();
    sairDesmatamento();
    sairSujeita();
    sairTraficoAnimais();
}
function mostrarTudo(){
    $("#floresta").show();
    sairQueimadas();
    sairDesmatamento();
    $("#animais").show();
    $("#reflorestamento").show();
    $("#lago").show();
    $("#greenpeace").show();
    $("#main_div").addClass("principal");
    $("#main_div").removeClass("floresta");
    $("#main_div").removeClass("animais");
    $("#main_div").removeClass("reflorestamento");
    $("#main_div").removeClass("lago");
    $("#main_div").removeClass("greenpeace");
    $("#voltar").hide();
}
$("#voltar").hide();
$("#floresta").click(function(){
    $("#main_div").addClass("queimada");
    esconderTudo();
    inicarQueimadas();
});
$("#lago").click(function(){
    esconderTudo();
    $("#main_div").addClass("sujeira");
    iniciarSujeira();
});
$("#animais").click(function(){
    $("#main_div").addClass("animais");
    esconderTudo();
    iniciarTraficoAnimais();
});
$("#reflorestamento").click(function(){
    $("#main_div").addClass("reflorestamento");
    esconderTudo();
    $("#desmatamento").show();
});
$("#lago").click(function(){
    $("#main_div").addClass("lago");
    esconderTudo();
});
$("#greenpeace").click(function(){
    $("#main_div").addClass("greenpeace");
    esconderTudo();
});
$("#voltar").click(function(){
    sairJogos();
    esconderTudo();
    mostrarTudo();
});